topics:
  -
    topic: /tf_static
    type: tf2_msgs/msg/TFMessage
    queue_size: 1
    qos:
      history: keep_all
      #reliability: reliable  # OR best_effort
      durability: transient_local  # OR volatile
  
  - 
    topic: /tf
    type: tf2_msgs/msg/TFMessage
    queue_size: 1

  -
    topic: /joint_states
    type: sensor_msgs/msg/JointState
    queue_size: 1

  -
    topic: /D415/color/image_raw
    type: sensor_msgs/msg/Image
    queue_size: 1

  -
    topic:  /D415/color/image_aruco/compressed
    type: sensor_msgs/msg/CompressedImage
    queue_size: 1


services_1_to_2:
  -
    service: /moveit_sim_service # ROS 2 service name
    type: std_srvs/srv/SetBool  # The ROS 2 service type name
  -
    service: /planning_scene_cp25 # ROS 2 service name
    type: std_srvs/srv/Empty  # The ROS 2 service type name
